DROP DATABASE IF EXISTS Whib;

CREATE DATABASE IF NOT EXISTS Whib;

USE Whib;

CREATE TABLE IF NOT EXISTS Region (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RegionType TINYINT NOT NULL,
    EnglishName NVARCHAR(200) NOT NULL UNIQUE,
    LocalName NVARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS Traveller (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Email NVARCHAR(200) NOT NULL UNIQUE,
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    BirthDate DATE,
    Nationality_RegionId INT,
    Residence_RegionId INT
);

SHOW TABLES;